CREATE SCHEMA IF NOT EXISTS ICP_dictionaries;

SET search_path TO ICP_dictionaries;

DROP TABLE IF EXISTS d_altitude; CREATE TABLE d_altitude ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL, value_min smallint  NULL, value_max smallint  NULL);
DROP TABLE IF EXISTS d_country; CREATE TABLE d_country ( code smallint  NOT NULL, lib_country character varying(250)  NULL, code_iso character varying(2)  NULL, code_fimci smallint  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL, eu boolean DEFAULT false NULL);
DROP TABLE IF EXISTS d_depth_level_soil; CREATE TABLE d_depth_level_soil ( code character varying(4)  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_determination_so; CREATE TABLE d_determination_so ( code character varying(4)  NOT NULL, description character varying(200)  NULL, category character varying(50)  NULL, valid_from_survey_year smallint  NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_ground_water_table; CREATE TABLE d_ground_water_table ( code smallint  NOT NULL, description character varying(220)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_hori_disc; CREATE TABLE d_hori_disc ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_hori_distinct; CREATE TABLE d_hori_distinct ( code smallint  NOT NULL, description character varying(250)  NULL, thickness_of_boundary_zone character varying(50)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_hori_topography; CREATE TABLE d_hori_topography ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_humus; CREATE TABLE d_humus ( code smallint  NOT NULL, description character varying(250)  NULL, description_fscc character varying(500)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_parameter_so; CREATE TABLE d_parameter_so ( code character varying(10)  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL, unit character varying(10)  NULL);
DROP TABLE IF EXISTS d_parent_material; CREATE TABLE d_parent_material ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_pretreatment_so; CREATE TABLE d_pretreatment_so ( code character varying(4)  NOT NULL, description character varying(200)  NULL, category character varying(50)  NULL, valid_from_survey_year smallint  NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_root_abundance; CREATE TABLE d_root_abundance ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL, very_fine character varying(10)  NULL, fine character varying(10)  NULL, medium character varying(10)  NULL, coarse character varying(10)  NULL);
DROP TABLE IF EXISTS d_sample_prep_so; CREATE TABLE d_sample_prep_so ( code character varying(4)  NOT NULL, description character varying(200)  NULL, category character varying(50)  NULL, valid_from_survey_year smallint  NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_soil_adjective; CREATE TABLE d_soil_adjective ( code character varying(3)  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL, fao_1988 smallint  NULL, wrb_1998 smallint  NULL, wrb_2006_2007 smallint  NULL, wrb_2014_2015 smallint  NULL);
DROP TABLE IF EXISTS d_soil_coarse_fragments; CREATE TABLE d_soil_coarse_fragments ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_soil_code_porosity; CREATE TABLE d_soil_code_porosity ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_soil_group; CREATE TABLE d_soil_group ( code character varying(2)  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_soil_specifier; CREATE TABLE d_soil_specifier ( code character varying(1)  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL, wrb_1998 smallint DEFAULT 0 NULL, wrb_2006_2007 smallint DEFAULT 0 NULL, wrb_2014_2015 smallint DEFAULT 0 NULL);
DROP TABLE IF EXISTS d_soil_structure; CREATE TABLE d_soil_structure ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_texture_class; CREATE TABLE d_texture_class ( code character varying(11)  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_water; CREATE TABLE d_water ( code smallint  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_water_table_type; CREATE TABLE d_water_table_type ( code smallint  NOT NULL, description character varying(220)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
DROP TABLE IF EXISTS d_wrb_diagnostics; CREATE TABLE d_wrb_diagnostics ( code character varying(3)  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL, type character varying  NULL);
DROP TABLE IF EXISTS d_wrb_pub; CREATE TABLE d_wrb_pub ( code character varying(8)  NOT NULL, description character varying(250)  NULL, valid_from_survey_year smallint  NOT NULL, valid_to_survey_year smallint  NULL);
